FROM eclipse-temurin:21-jre
WORKDIR /app
COPY marketing-cost-biz/target/marketing-cost-biz-0.0.1-SNAPSHOT.jar /app/app.jar
EXPOSE 8081
ENTRYPOINT ["java", \
  "-Xms6g", "-Xmx6g", \
  "-XX:+UseG1GC", \
  "-jar", "/app/app.jar"]
