package com.sanhua.marketingcost.service.collaboration;

public enum CollaborationNextAction {
  SUPPLEMENT_BOM,
  VERIFY_ELECTRONIC_BOM,
  SUPPLEMENT_PACKAGE,
  SUPPLEMENT_PRICE,
  FIX_VALIDATION_ERRORS,
  SUBMIT_FINANCE_REVIEW,
  WAIT_FINANCE,
  REVIEW_TECH_SUBMISSION,
  REVISE_RETURNED_ITEMS,
  RETRY_PUBLISH_OR_REPRICE,
  START_COSTING,
  CONTINUE_COSTING,
  NONE
}
