CREATE TABLE oa_form (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  oa_no VARCHAR(64) NOT NULL,
  form_type VARCHAR(64),
  apply_date DATE,
  customer VARCHAR(255),
  copper_price DECIMAL(12,2),
  zinc_price DECIMAL(12,2),
  aluminum_price DECIMAL(12,2),
  steel_price DECIMAL(12,2),
  other_material DECIMAL(12,2),
  base_shipping DECIMAL(12,2),
  sale_link VARCHAR(255),
  remark VARCHAR(500),
  created_at DATETIME,
  updated_at DATETIME,
  deleted TINYINT(1) DEFAULT 0,
  UNIQUE KEY uk_oa_form_oa_no (oa_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE oa_form_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  oa_form_id BIGINT NOT NULL,
  seq INT,
  product_name VARCHAR(255),
  customer_drawing VARCHAR(255),
  material_no VARCHAR(255),
  sunl_model VARCHAR(255),
  spec VARCHAR(255),
  shipping_fee DECIMAL(12,4),
  support_qty DECIMAL(12,4),
  total_with_ship DECIMAL(12,4),
  total_no_ship DECIMAL(12,4),
  material_cost DECIMAL(12,4),
  labor_cost DECIMAL(12,4),
  manufacturing_cost DECIMAL(12,4),
  management_cost DECIMAL(12,4),
  valid_date DATE,
  created_at DATETIME,
  updated_at DATETIME,
  deleted TINYINT(1) DEFAULT 0,
  KEY idx_oa_form_id (oa_form_id),
  KEY idx_oa_form_material (oa_form_id, material_no),
  KEY idx_oa_form_drawing (oa_form_id, customer_drawing),
  KEY idx_oa_form_model_spec (oa_form_id, sunl_model, spec)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE lp_cost_run_cost_item (
  id BIGINT NOT NULL AUTO_INCREMENT,
  oa_no VARCHAR(64) NOT NULL,
  product_code VARCHAR(64) NOT NULL,
  line_no INT DEFAULT NULL,
  cost_code VARCHAR(40) NOT NULL,
  cost_name VARCHAR(120) NOT NULL,
  base_amount DECIMAL(18,6) DEFAULT NULL,
  rate DECIMAL(10,6) DEFAULT NULL,
  amount DECIMAL(18,6) DEFAULT NULL,
  source_table VARCHAR(64) DEFAULT NULL,
  source_id BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cost_run_cost (oa_no, product_code),
  KEY idx_cost_run_cost_code (cost_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE lp_cost_run_result (
  id BIGINT NOT NULL AUTO_INCREMENT,
  oa_no VARCHAR(64) NOT NULL,
  product_code VARCHAR(64) NOT NULL,
  product_name VARCHAR(120) DEFAULT NULL,
  product_model VARCHAR(120) DEFAULT NULL,
  customer_name VARCHAR(120) DEFAULT NULL,
  business_unit VARCHAR(120) DEFAULT NULL,
  department VARCHAR(120) DEFAULT NULL,
  period VARCHAR(7) NOT NULL,
  currency VARCHAR(10) DEFAULT NULL,
  unit VARCHAR(20) DEFAULT NULL,
  total_cost DECIMAL(18,6) DEFAULT NULL,
  calc_status VARCHAR(20) NOT NULL,
  calc_at DATETIME DEFAULT NULL,
  product_attr VARCHAR(120) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cost_run_result (oa_no, product_code, period),
  KEY idx_cost_run_oa (oa_no),
  KEY idx_cost_run_period (period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed data for OA form headers and key detail items.
INSERT INTO oa_form (
  oa_no,
  form_type,
  apply_date,
  customer,
  copper_price,
  zinc_price,
  aluminum_price,
  steel_price,
  other_material,
  base_shipping,
  sale_link,
  remark,
  created_at,
  updated_at,
  deleted
) VALUES
  (
    'FI-SR-005-20260116-0527',
    '家用-FI-SR-005',
    '2026-01-16',
    'YEONGJIN KOREA CO.,LTD.',
    100000.00,
    24662.00,
    NULL,
    NULL,
    NULL,
    10615.00,
    '销售价格固定',
    '100000元/T 电解铜时成本',
    NOW(),
    NOW(),
    0
  ),
  (
    'FI-SC-006-20260120-0118',
    '商用-FI-SC-006',
    '2026-01-20',
    'COMMERCIAL TECH CO.,LTD.',
    98000.00,
    24200.00,
    22000.00,
    18000.00,
    5000.00,
    9800.00,
    NULL,
    NULL,
    NOW(),
    NOW(),
    0
  );

INSERT INTO oa_form_item (
  oa_form_id,
  seq,
  product_name,
  customer_drawing,
  material_no,
  sunl_model,
  spec,
  shipping_fee,
  support_qty,
  total_with_ship,
  total_no_ship,
  material_cost,
  labor_cost,
  manufacturing_cost,
  management_cost,
  valid_date,
  created_at,
  updated_at,
  deleted
) VALUES
  (
    (SELECT id FROM oa_form WHERE oa_no = 'FI-SR-005-20260116-0527'),
    1,
    '产品A',
    '图号A',
    '料号A',
    '型号A',
    '规格A',
    0.30,
    12.00,
    5.26,
    4.96,
    2.10,
    0.60,
    0.80,
    0.40,
    '2026-12-31',
    NOW(),
    NOW(),
    0
  ),
  (
    (SELECT id FROM oa_form WHERE oa_no = 'FI-SR-005-20260116-0527'),
    2,
    '产品B',
    '图号B',
    '料号B',
    '型号B',
    '规格B',
    0.20,
    8.50,
    4.10,
    3.90,
    1.80,
    0.50,
    0.60,
    0.30,
    '2026-12-31',
    NOW(),
    NOW(),
    0
  );
