-- ============================================================================
-- V206: 报价 BOM 与价格协作基础表
--
-- 仅创建协作编排所需的 12 张新表：
-- - 不修改任何现有表结构；
-- - 不写入业务数据、菜单数据或模拟数据；
-- - 与现有业务对象保持逻辑关联，不创建跨模块物理外键。
-- ============================================================================

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `collaboration_no` VARCHAR(64) NOT NULL COMMENT '协作主任务号',
  `oa_form_id` BIGINT NOT NULL COMMENT '报价表头ID',
  `oa_no` VARCHAR(64) NOT NULL COMMENT '报价/OA单号',
  `round_no` INT NOT NULL DEFAULT 1 COMMENT '同一报价协作轮次',
  `business_unit_type` VARCHAR(32) NULL COMMENT '业务单元',
  `accounting_month` CHAR(7) NOT NULL COMMENT '核算月份YYYY-MM',
  `source_system` VARCHAR(32) NOT NULL DEFAULT 'QUOTE_COST' COMMENT '任务来源',
  `master_status` VARCHAR(32) NOT NULL COMMENT '主任务状态',
  `finance_reviewer_user_id` BIGINT NULL COMMENT '财务审核人用户ID',
  `finance_reviewer_name` VARCHAR(128) NULL COMMENT '财务审核人姓名快照',
  `current_review_id` BIGINT NULL COMMENT '当前审核记录ID',
  `owned_product_count` INT NOT NULL DEFAULT 0 COMMENT '归属产品数',
  `tech_submitted_count` INT NOT NULL DEFAULT 0 COMMENT '技术已提交产品数',
  `returned_product_count` INT NOT NULL DEFAULT 0 COMMENT '被退回产品数',
  `ready_product_count` INT NOT NULL DEFAULT 0 COMMENT '数据准备完成产品数',
  `task_version` INT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
  `oa_process_instance_id` VARCHAR(128) NULL COMMENT '未来OA流程实例ID',
  `last_error_code` VARCHAR(64) NULL COMMENT '最近异常码',
  `last_error_message` VARCHAR(1000) NULL COMMENT '最近异常说明',
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collaboration_no` (`collaboration_no`),
  UNIQUE KEY `uk_collaboration_form_round` (`oa_form_id`, `round_no`),
  KEY `idx_collaboration_finance` (`finance_reviewer_user_id`, `master_status`),
  KEY `idx_collaboration_oa_status` (`oa_no`, `master_status`),
  KEY `idx_collaboration_bu_month` (`business_unit_type`, `accounting_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价单级BOM与价格协作主任务';

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_product_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_task_no` VARCHAR(64) NOT NULL COMMENT '产品协作任务号',
  `origin_collaboration_id` BIGINT NOT NULL COMMENT '最初创建任务的主任务ID',
  `accounting_month` CHAR(7) NOT NULL COMMENT '任务创建月份YYYY-MM',
  `business_unit_type` VARCHAR(32) NULL COMMENT '业务单元',
  `applicable_org_code` VARCHAR(64) NOT NULL COMMENT '活动锁及价格适用组织',
  `material_org_code` VARCHAR(64) NULL COMMENT 'U9物料组织',
  `price_org_code` VARCHAR(64) NULL COMMENT 'U9 BOM/价格组织',
  `product_code` VARCHAR(64) NULL COMMENT '产品料号',
  `temporary_product_key` VARCHAR(64) NULL COMMENT '新品无料号时的稳定临时键',
  `product_name` VARCHAR(255) NULL COMMENT '产品名称快照',
  `product_spec` VARCHAR(255) NULL COMMENT '规格快照',
  `product_model` VARCHAR(255) NULL COMMENT '型号快照',
  `product_form` VARCHAR(32) NOT NULL COMMENT 'NORMAL/BARE/UNKNOWN',
  `primary_scope` VARCHAR(32) NOT NULL COMMENT 'FULL_BOM/BARE_PACKAGE/PRICE_ONLY',
  `need_bom` TINYINT(1) NOT NULL DEFAULT 0,
  `need_package` TINYINT(1) NOT NULL DEFAULT 0,
  `need_price` TINYINT(1) NOT NULL DEFAULT 0,
  `open_gap_count` INT NOT NULL DEFAULT 0,
  `task_status` VARCHAR(32) NOT NULL COMMENT '产品任务状态',
  `original_technician_user_id` BIGINT NOT NULL COMMENT '原技术负责人用户ID',
  `original_technician_name` VARCHAR(128) NULL,
  `current_assignee_user_id` BIGINT NULL COMMENT '当前责任人用户ID',
  `current_assignee_name` VARCHAR(128) NULL,
  `task_version` INT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
  `active_lock_key` VARCHAR(255) NULL COMMENT '活动任务去重键，终态置空',
  `active_flag` TINYINT(1) NOT NULL DEFAULT 1,
  `preparation_id` BIGINT NULL COMMENT 'BOM准备记录ID',
  `supplement_version_id` BIGINT NULL COMMENT 'BOM补录版本ID',
  `package_reference_id` BIGINT NULL COMMENT '裸品包装参考ID',
  `electronic_bom_fingerprint` CHAR(64) NULL COMMENT '电子图库BOM指纹',
  `last_validation_status` VARCHAR(32) NULL COMMENT 'NOT_CHECKED/PASSED/FAILED',
  `last_validation_at` DATETIME NULL,
  `tech_submitted_at` DATETIME NULL,
  `ready_at` DATETIME NULL,
  `cancel_reason` VARCHAR(500) NULL,
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_task_no` (`product_task_no`),
  UNIQUE KEY `uk_product_task_active_lock` (`active_lock_key`),
  KEY `idx_product_task_origin` (`origin_collaboration_id`),
  KEY `idx_product_task_owner` (`current_assignee_user_id`, `task_status`),
  KEY `idx_product_task_product` (`product_code`, `applicable_org_code`, `accounting_month`),
  KEY `idx_product_task_status` (`task_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价产品级BOM与价格协作任务';

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_quote_link` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_task_id` BIGINT NOT NULL COMMENT '产品任务ID',
  `collaboration_id` BIGINT NOT NULL COMMENT '当前报价主任务ID',
  `oa_form_id` BIGINT NOT NULL COMMENT '报价表头ID',
  `oa_form_item_id` BIGINT NOT NULL COMMENT '报价产品行ID',
  `oa_no` VARCHAR(64) NOT NULL COMMENT '报价单号',
  `product_code` VARCHAR(64) NULL COMMENT '产品料号快照',
  `accounting_month` CHAR(7) NOT NULL COMMENT '报价核算月份',
  `applicable_org_code` VARCHAR(64) NOT NULL COMMENT '报价适用组织',
  `link_type` VARCHAR(32) NOT NULL COMMENT 'OWNER/ACTIVE_TASK_LINK/APPROVED_RESULT_REUSE',
  `approved_result_id` BIGINT NULL COMMENT '直接复用的审核结果ID',
  `link_status` VARCHAR(32) NOT NULL COMMENT 'WAIT_SOURCE/RECHECKING/READY/FAILED/CANCELLED',
  `latest_price_prepare_no` VARCHAR(64) NULL COMMENT '最近价格复验批次',
  `reprice_gap_count` INT NOT NULL DEFAULT 0,
  `ready_at` DATETIME NULL,
  `active_flag` TINYINT(1) NOT NULL DEFAULT 1,
  `active_link_key` VARCHAR(128) NULL COMMENT 'OA_ITEM:{oa_form_item_id}，历史置空',
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collaboration_quote_link_active` (`active_link_key`),
  KEY `idx_quote_link_product_task` (`product_task_id`),
  KEY `idx_quote_link_collaboration` (`collaboration_id`),
  KEY `idx_quote_link_item` (`oa_form_item_id`, `active_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='协作产品任务与报价产品行关联';

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_gap` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `gap_no` VARCHAR(64) NOT NULL COMMENT '缺口编号',
  `product_task_id` BIGINT NOT NULL COMMENT '产品任务ID',
  `gap_category` VARCHAR(32) NOT NULL COMMENT 'BOM/PACKAGE/PRICE',
  `gap_type` VARCHAR(64) NOT NULL COMMENT '结构化缺口类型',
  `source_type` VARCHAR(64) NULL COMMENT '缺口来源类型',
  `source_id` BIGINT NULL COMMENT '来源记录ID',
  `gap_fingerprint` CHAR(64) NOT NULL COMMENT '任务内缺口幂等指纹',
  `bom_node_key` VARCHAR(128) NULL,
  `bom_path` VARCHAR(2000) NULL,
  `material_code` VARCHAR(64) NULL COMMENT '真正需处理料号',
  `material_name` VARCHAR(255) NULL,
  `material_spec` VARCHAR(255) NULL,
  `material_model` VARCHAR(255) NULL,
  `material_role` VARCHAR(32) NULL COMMENT 'NORMAL/RAW/SCRAP/PACKAGE',
  `suggested_price_type` VARCHAR(32) NULL COMMENT '建议价格类型，不代替技术选择',
  `reason_code` VARCHAR(64) NOT NULL,
  `reason_message` VARCHAR(1000) NOT NULL,
  `gap_status` VARCHAR(32) NOT NULL COMMENT 'OPEN/DRAFT_READY/RESOLVED/WAIVED/OBSOLETE',
  `current_price_draft_id` BIGINT NULL,
  `resolved_at` DATETIME NULL,
  `resolved_by` BIGINT NULL,
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collaboration_gap_no` (`gap_no`),
  UNIQUE KEY `uk_task_gap_fingerprint` (`product_task_id`, `gap_fingerprint`),
  KEY `idx_collaboration_gap_status` (`product_task_id`, `gap_status`),
  KEY `idx_collaboration_gap_material` (`material_code`, `gap_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='BOM包装校验问题及真实价格缺口';

CREATE TABLE IF NOT EXISTS `lp_quote_price_draft` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `draft_no` VARCHAR(64) NOT NULL COMMENT '价格草稿编号',
  `product_task_id` BIGINT NOT NULL COMMENT '产品任务ID',
  `gap_id` BIGINT NOT NULL COMMENT '真实缺价ID',
  `material_code` VARCHAR(64) NOT NULL COMMENT '目标料号',
  `material_name` VARCHAR(255) NULL,
  `material_spec` VARCHAR(255) NULL,
  `material_model` VARCHAR(255) NULL,
  `business_unit_type` VARCHAR(32) NULL,
  `org_code` VARCHAR(64) NOT NULL COMMENT '正式价格适用组织',
  `price_type` VARCHAR(32) NOT NULL COMMENT 'FIXED_PURCHASE/LINKED/RANGE/SETTLE_FIXED',
  `source_mode` VARCHAR(16) NOT NULL COMMENT 'COPY/DIRECT',
  `reference_source_type` VARCHAR(64) NULL,
  `reference_source_id` BIGINT NULL,
  `reference_version_text` VARCHAR(128) NULL,
  `target_source_type` VARCHAR(64) NOT NULL COMMENT '目标正式价格源类型',
  `supplier_code` VARCHAR(64) NULL,
  `supplier_name` VARCHAR(255) NULL,
  `unit` VARCHAR(32) NULL,
  `tax_included` TINYINT(1) NULL,
  `tax_rate` DECIMAL(10,6) NULL,
  `effective_from` DATE NULL,
  `effective_to` DATE NULL,
  `draft_status` VARCHAR(32) NOT NULL COMMENT 'EDITING/VALIDATED/SUBMITTED/APPROVED/REJECTED/PUBLISHED/VOIDED',
  `validation_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_CHECKED',
  `validation_message` VARCHAR(1000) NULL,
  `draft_version` INT NOT NULL DEFAULT 1,
  `draft_fingerprint` CHAR(64) NULL,
  `submitted_at` DATETIME NULL,
  `published_source_table` VARCHAR(64) NULL,
  `published_source_id` BIGINT NULL,
  `publish_batch_no` VARCHAR(64) NULL,
  `published_at` DATETIME NULL,
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quote_price_draft_no` (`draft_no`),
  KEY `idx_price_draft_product_task` (`product_task_id`, `draft_status`),
  KEY `idx_price_draft_gap` (`gap_id`),
  KEY `idx_price_draft_material` (`material_code`, `org_code`),
  KEY `idx_price_draft_publish_batch` (`publish_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='技术补价草稿主表';

CREATE TABLE IF NOT EXISTS `lp_quote_price_draft_field` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `price_draft_id` BIGINT NOT NULL COMMENT '价格草稿ID',
  `section_code` VARCHAR(64) NOT NULL COMMENT 'COMMON/FORMULA/VARIABLE/RANGE_ROW',
  `row_key` VARCHAR(64) NOT NULL DEFAULT 'MAIN',
  `field_code` VARCHAR(128) NOT NULL COMMENT '稳定字段编码',
  `field_name` VARCHAR(128) NULL,
  `value_type` VARCHAR(16) NOT NULL COMMENT 'TEXT/DECIMAL/DATE/BOOLEAN/JSON',
  `reference_value_json` JSON NULL,
  `target_value_json` JSON NULL,
  `unit` VARCHAR(32) NULL,
  `required_flag` TINYINT(1) NOT NULL DEFAULT 0,
  `tech_input_required` TINYINT(1) NOT NULL DEFAULT 0,
  `changed_flag` TINYINT(1) NOT NULL DEFAULT 0,
  `validation_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_CHECKED',
  `validation_message` VARCHAR(500) NULL,
  `sort_seq` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_price_draft_field` (`price_draft_id`, `section_code`, `row_key`, `field_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='四类价格草稿字段及区间行';

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `review_no` VARCHAR(64) NOT NULL COMMENT '审核编号',
  `collaboration_id` BIGINT NOT NULL COMMENT '协作主任务ID',
  `review_round` INT NOT NULL DEFAULT 1,
  `review_status` VARCHAR(32) NOT NULL COMMENT 'PENDING/PARTIAL/REJECTED/APPROVED/PUBLISHING/EFFECTIVE/FAILED',
  `reviewer_user_id` BIGINT NOT NULL COMMENT '财务审核人用户ID',
  `reviewer_name` VARCHAR(128) NULL,
  `source_task_version` INT NOT NULL COMMENT '生成审核时主任务版本',
  `product_count` INT NOT NULL,
  `price_draft_count` INT NOT NULL,
  `passed_item_count` INT NOT NULL DEFAULT 0,
  `rejected_item_count` INT NOT NULL DEFAULT 0,
  `review_comment` VARCHAR(1000) NULL,
  `publish_batch_no` VARCHAR(64) NULL COMMENT '正式发布幂等批次',
  `submitted_at` DATETIME NULL,
  `reviewed_at` DATETIME NULL,
  `effective_at` DATETIME NULL,
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collaboration_review_no` (`review_no`),
  UNIQUE KEY `uk_review_round` (`collaboration_id`, `review_round`),
  UNIQUE KEY `uk_review_publish_batch` (`publish_batch_no`),
  KEY `idx_collaboration_review_reviewer` (`reviewer_user_id`, `review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='整单财务审核主记录';

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_review_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `review_id` BIGINT NOT NULL COMMENT '审核主记录ID',
  `product_task_id` BIGINT NOT NULL COMMENT '产品任务ID',
  `item_type` VARCHAR(32) NOT NULL COMMENT 'PRODUCT/BOM/PACKAGE/PRICE_DRAFT',
  `item_ref_id` BIGINT NOT NULL,
  `item_version` INT NOT NULL,
  `item_summary` VARCHAR(1000) NULL,
  `difference_snapshot_json` JSON NULL,
  `validation_snapshot_json` JSON NULL,
  `decision` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/PASSED/REJECTED',
  `decision_reason` VARCHAR(1000) NULL,
  `decided_by` BIGINT NULL,
  `decided_by_name` VARCHAR(128) NULL,
  `decided_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_item` (`review_id`, `item_type`, `item_ref_id`, `item_version`),
  KEY `idx_review_item_product_task` (`product_task_id`, `decision`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务审核产品BOM包装及价格项';

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_approved_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `result_no` VARCHAR(64) NOT NULL COMMENT '审核结果编号',
  `result_type` VARCHAR(32) NOT NULL COMMENT 'FULL_BOM/BARE_PACKAGE',
  `source_product_task_id` BIGINT NOT NULL,
  `source_review_id` BIGINT NOT NULL,
  `product_code` VARCHAR(64) NOT NULL,
  `product_form` VARCHAR(32) NOT NULL,
  `applicable_org_code` VARCHAR(64) NOT NULL,
  `source_object_type` VARCHAR(64) NOT NULL COMMENT 'SUPPLEMENT_VERSION/PACKAGE_REFERENCE',
  `source_object_id` BIGINT NOT NULL,
  `source_system` VARCHAR(32) NOT NULL COMMENT 'ELECTRONIC_DRAWING/QUOTE_PACKAGE',
  `source_version_text` VARCHAR(128) NULL,
  `structure_fingerprint` CHAR(64) NOT NULL,
  `u9_context_fingerprint` CHAR(64) NULL,
  `validity_policy_code` VARCHAR(64) NOT NULL,
  `validity_months` INT NOT NULL DEFAULT 6,
  `valid_from` DATETIME NOT NULL,
  `valid_until` DATETIME NOT NULL,
  `result_status` VARCHAR(32) NOT NULL COMMENT 'ACTIVE/EXPIRED/REVOKED/INVALIDATED',
  `invalid_reason` VARCHAR(500) NULL,
  `invalidated_at` DATETIME NULL,
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collaboration_approved_result_no` (`result_no`),
  KEY `idx_approved_result_match` (`product_code`, `applicable_org_code`, `result_type`, `result_status`, `valid_until`),
  KEY `idx_approved_result_source_task` (`source_product_task_id`),
  KEY `idx_approved_result_source_review` (`source_review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='半年内可复用的BOM或裸品包装结果';

CREATE TABLE IF NOT EXISTS `lp_quote_collaboration_external_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `external_system` VARCHAR(32) NOT NULL DEFAULT 'OA',
  `collaboration_id` BIGINT NOT NULL,
  `product_task_id` BIGINT NULL COMMENT '技术待办有值，整单财务待办可空',
  `task_kind` VARCHAR(32) NOT NULL COMMENT 'TECH/TECH_REWORK/FINANCE/NOTICE',
  `logical_task_version` INT NOT NULL,
  `external_process_id` VARCHAR(128) NULL,
  `external_task_id` VARCHAR(128) NULL,
  `external_status` VARCHAR(32) NOT NULL COMMENT 'NOT_CREATED/HOLD/OPEN/DONE/CLOSED/FAILED',
  `assignee_user_id` VARCHAR(64) NULL COMMENT '外部稳定人员ID',
  `assignee_name` VARCHAR(128) NULL,
  `entry_url` VARCHAR(500) NULL,
  `current_flag` TINYINT(1) NOT NULL DEFAULT 1,
  `opened_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `last_sync_at` DATETIME NULL,
  `last_error_message` VARCHAR(1000) NULL,
  `created_by` BIGINT NULL,
  `created_by_name` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL,
  `updated_by_name` VARCHAR(128) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_external_task_id` (`external_task_id`),
  KEY `idx_external_task_collaboration` (`collaboration_id`, `task_kind`, `current_flag`),
  KEY `idx_external_task_product` (`product_task_id`, `current_flag`),
  KEY `idx_external_task_assignee` (`assignee_user_id`, `external_status`),
  KEY `idx_external_task_dispatch` (`external_system`, `external_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='未来OA技术及财务待办绑定';

CREATE TABLE IF NOT EXISTS `lp_integration_outbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` CHAR(36) NOT NULL COMMENT '事件UUID',
  `idempotency_key` VARCHAR(255) NOT NULL COMMENT '业务幂等键',
  `destination` VARCHAR(32) NOT NULL,
  `aggregate_type` VARCHAR(64) NOT NULL,
  `aggregate_id` BIGINT NOT NULL,
  `aggregate_version` INT NOT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `event_version` VARCHAR(16) NOT NULL DEFAULT '1.0',
  `payload_json` JSON NOT NULL,
  `payload_hash` CHAR(64) NOT NULL,
  `send_policy` VARCHAR(16) NOT NULL COMMENT 'AUTO/HOLD',
  `send_status` VARCHAR(16) NOT NULL COMMENT 'HOLD/PENDING/SENDING/SENT/FAILED/DEAD',
  `retry_count` INT NOT NULL DEFAULT 0,
  `next_retry_at` DATETIME NULL,
  `last_http_status` INT NULL,
  `response_json` JSON NULL,
  `last_error_message` VARCHAR(1000) NULL,
  `occurred_at` DATETIME NOT NULL,
  `sent_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outbox_event_id` (`event_id`),
  UNIQUE KEY `uk_outbox_idempotency_key` (`idempotency_key`),
  KEY `idx_outbox_dispatch` (`destination`, `send_status`, `next_retry_at`),
  KEY `idx_outbox_aggregate` (`aggregate_type`, `aggregate_id`, `aggregate_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部集成可靠发件箱';

CREATE TABLE IF NOT EXISTS `lp_integration_inbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `source_system` VARCHAR(32) NOT NULL,
  `callback_id` VARCHAR(128) NOT NULL COMMENT '外部回调ID',
  `idempotency_key` VARCHAR(255) NOT NULL COMMENT '回调幂等键',
  `callback_type` VARCHAR(64) NOT NULL,
  `payload_json` JSON NOT NULL,
  `payload_hash` CHAR(64) NOT NULL,
  `signature_status` VARCHAR(16) NOT NULL COMMENT 'NOT_CHECKED/PASSED/FAILED',
  `process_status` VARCHAR(16) NOT NULL COMMENT 'RECEIVED/PROCESSED/REJECTED/FAILED',
  `process_message` VARCHAR(1000) NULL,
  `received_at` DATETIME NOT NULL,
  `processed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_inbox_callback_id` (`callback_id`),
  UNIQUE KEY `uk_inbox_idempotency_key` (`idempotency_key`),
  KEY `idx_inbox_process` (`source_system`, `process_status`, `received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部回调幂等与处理结果';
