-- 补录价格复用正式存储；来源分类不改变原公共记录、审批内容或冻结成本。
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_fixed_item' AND column_name='source_kind'), 'SELECT 1', 'ALTER TABLE lp_price_fixed_item ADD COLUMN source_kind VARCHAR(32) NOT NULL DEFAULT ''PUBLIC''');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_fixed_item' AND column_name='technical_version_id'), 'SELECT 1', 'ALTER TABLE lp_price_fixed_item ADD COLUMN technical_version_id BIGINT NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_fixed_item' AND column_name='technical_item_key'), 'SELECT 1', 'ALTER TABLE lp_price_fixed_item ADD COLUMN technical_item_key VARCHAR(64) NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_fixed_item' AND column_name='technical_publication_status'), 'SELECT 1', 'ALTER TABLE lp_price_fixed_item ADD COLUMN technical_publication_status VARCHAR(24) NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_fixed_item' AND column_name='technical_publication_message'), 'SELECT 1', 'ALTER TABLE lp_price_fixed_item ADD COLUMN technical_publication_message VARCHAR(1000) NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='lp_price_fixed_item' AND index_name='uk_tech_price_version_item'), 'SELECT 1', 'CREATE UNIQUE INDEX uk_tech_price_version_item ON lp_price_fixed_item(technical_version_id,technical_item_key)');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_linked_item' AND column_name='source_kind'), 'SELECT 1', 'ALTER TABLE lp_price_linked_item ADD COLUMN source_kind VARCHAR(32) NOT NULL DEFAULT ''PUBLIC''');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_linked_item' AND column_name='technical_version_id'), 'SELECT 1', 'ALTER TABLE lp_price_linked_item ADD COLUMN technical_version_id BIGINT NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_linked_item' AND column_name='technical_item_key'), 'SELECT 1', 'ALTER TABLE lp_price_linked_item ADD COLUMN technical_item_key VARCHAR(64) NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_linked_item' AND column_name='technical_publication_status'), 'SELECT 1', 'ALTER TABLE lp_price_linked_item ADD COLUMN technical_publication_status VARCHAR(24) NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lp_price_linked_item' AND column_name='technical_publication_message'), 'SELECT 1', 'ALTER TABLE lp_price_linked_item ADD COLUMN technical_publication_message VARCHAR(1000) NULL');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
SET @tw15_ddl = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='lp_price_linked_item' AND index_name='uk_tech_price_version_item'), 'SELECT 1', 'CREATE UNIQUE INDEX uk_tech_price_version_item ON lp_price_linked_item(technical_version_id,technical_item_key)');
PREPARE tw15_stmt FROM @tw15_ddl;
EXECUTE tw15_stmt;
DEALLOCATE PREPARE tw15_stmt;
-- 补录单价按最多十二位小数保存，避免发布时静默截成六位；原数值不变。
ALTER TABLE lp_price_fixed_item MODIFY fixed_price DECIMAL(24,12) NULL;
