-- 报价最终确认独立于技术送审；原成本版本及各步接口报文保留。
CREATE TABLE IF NOT EXISTS lp_quote_final_submission (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 oa_form_id BIGINT NOT NULL,
 oa_no VARCHAR(128) NOT NULL,
 accounting_month CHAR(7) NOT NULL,
 submission_round INT NOT NULL,
 source_system VARCHAR(64) NOT NULL,
 environment VARCHAR(32) NOT NULL,
 external_document_id VARCHAR(128) NOT NULL,
 external_flow_id VARCHAR(128),
 approver_external_id VARCHAR(128),
 business_unit_type VARCHAR(32) NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 current_step VARCHAR(32) NOT NULL DEFAULT 'QUOTE_STATUS',
 outbound_message_id BIGINT,
 step_attempt INT NOT NULL DEFAULT 0,
 content_fingerprint CHAR(64) NOT NULL,
 cost_snapshot_json JSON NOT NULL,
 operator_user_id BIGINT NOT NULL,
 operator_external_id VARCHAR(128) NOT NULL,
 return_sequence BIGINT NOT NULL DEFAULT 0,
 return_reason VARCHAR(512),
 error_message VARCHAR(512),
 submitted_at DATETIME(3),
 returned_at DATETIME(3),
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_quote_final_round (oa_form_id,accounting_month,submission_round),
 KEY idx_quote_final_message (outbound_message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
