-- OA 人员目录是技术补录选人的本地快照。外部查询失败时不更新本表。
CREATE TABLE IF NOT EXISTS lp_oa_person_directory (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source_system VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
  environment VARCHAR(32) COLLATE utf8mb4_bin NOT NULL,
  oa_user_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
  employee_no VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
  person_name VARCHAR(128) NOT NULL,
  position_name VARCHAR(128) NULL,
  position_id VARCHAR(64) COLLATE utf8mb4_bin NULL,
  employment_status VARCHAR(32) NULL,
  target_department_paths VARCHAR(1000) NOT NULL,
  actual_department_paths VARCHAR(2000) NOT NULL,
  oa_department_ids VARCHAR(1000) COLLATE utf8mb4_bin NOT NULL,
  target_department_ids VARCHAR(1000) COLLATE utf8mb4_bin NOT NULL,
  match_types VARCHAR(255) NOT NULL,
  system_user_id BIGINT NOT NULL,
  selectable_flag TINYINT(1) NOT NULL DEFAULT 1,
  active_flag TINYINT(1) NOT NULL DEFAULT 1,
  sync_batch_id CHAR(36) COLLATE ascii_bin NOT NULL,
  last_seen_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_oa_person_external (source_system, environment, oa_user_id),
  UNIQUE KEY uk_oa_person_employee (source_system, environment, employee_no),
  INDEX idx_oa_person_search_name (active_flag, selectable_flag, person_name),
  INDEX idx_oa_person_search_employee (active_flag, selectable_flag, employee_no),
  INDEX idx_oa_person_system_user (system_user_id, active_flag),
  INDEX idx_oa_person_sync_batch (source_system, environment, sync_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
