package com.sanhua.marketingcost.integration.oa;

import java.util.List;

/** 2026-09-17 Word I01 字段字典；只定义当前六种表单，不按 OA 控件类型猜值。 */
final class OaQuotationFields {
  private OaQuotationFields() {}

  record Field(String key, String label, boolean number, boolean optional) {}

  static final List<Field> SC005_MAIN =
      List.of(
          new Field("sqr", "申请人", false, false),
          new Field("sqsj", "申请时间", false, false),
          new Field("gh", "工号", false, false),
          new Field("sqdw", "申请单位", false, false),
          new Field("sqbm", "申请部门", false, false),
          new Field("sqcs", "申请处室", false, false),
          new Field("frzz", "法人组织", false, false),
          new Field("khmc", "客户名称", false, false),
          new Field("khbm", "U9客户编码", false, true),
          new Field("khjc", "客户简称", false, true),
          new Field("cpsx", "产品属性", false, false),
          new Field("yqwcjyssj", "要求完成建议书时间", false, false),
          new Field("khlx", "客户类型", false, false),
          new Field("hl", "汇率", true, false),
          new Field("mytk", "贸易条款", false, false),
          new Field("hyfhsbz", "运费核算标准（美元）", true, false),
          new Field("cpsyb", "产品事业部", false, false),
          new Field("jsy", "技术员", false, false),
          new Field("sftghwckfzdkh", "是否通过海外仓库发终端客户", false, false),
          new Field("sfyrzxq", "是否有认证需求", false, false),
          new Field("crmsjbm", "CRM商机编码", false, false),
          new Field("khxqrzxm", "客户需求认证项目", false, false),
          new Field("tjldfs", "销售价格是否联动", false, false),
          new Field("ywbm", "业务部门", false, false),
          new Field("djtjg", "电解铜价格（含税 元/吨）", true, false),
          new Field("djxjg", "电解锌价格（含税 元/吨）", true, false),
          new Field("hssljjhs", "核算时铝基价（含税 元/吨）", true, false),
          new Field("hsssus316jjh", "核算时SUS316基价（含税 元/吨）", true, false),
          new Field("hsssus304jjh", "核算时SUS304基价（含税 元/吨）", true, false),
          new Field("mjfyscd1", "模具费由谁承担", false, false),
          new Field("cpzt1", "产品状态（同名字段之一）", false, false),
          new Field("khzdcgsm", "客户指定采购说明", false, false),
          new Field("rzfjehsy", "认证费金额（含税 元）", true, false),
          new Field("gzjjfyzjey", "工装夹具费用 总金额（含税 元）", true, false),
          new Field("mjfyzjey", "模具费用总金额（含税 元）", true, false),
          new Field("mjfgs1", "模具费归属", false, false),
          new Field("djfyyz", "刀具费用（元/只）", true, false),
          new Field("yfxmh", "研发项目号", false, false),
          new Field("djgzyz", "单件工资（元/只）", true, false),
          new Field("jssl", "净损失率（%）", true, false),
          new Field("cpzt11", "产品状态（同名字段之二）", false, false),
          new Field("htpsddh", "合同评审单单号", false, false),
          new Field("lb1", "类别", false, false),
          new Field("kxxfx", "可行性分析", false, false),
          new Field("bz", "备注（辅助信息）", false, false));
  static final List<Field> SC005_ITEM =
      List.of(
          new Field("wlxzx", "物料选择新", false, false),
          new Field("lh", "料号", false, false),
          new Field("cpmc", "产品名称", false, false),
          new Field("shxh", "三花型号", false, false),
          new Field("u11wm", "U11位码", false, false),
          new Field("ysfyz", "运输费 [元/只]", true, false),
          new Field("yjnylwz", "预计年用量 [万只]", true, false),
          new Field("bzfs", "包装方式", false, false),
          new Field("mbxsjg", "目标销售价格（不含税，元/只）", true, false),
          new Field("hyfzcbbhs", "含运费总成本(不含税) （元/只）", true, false),
          new Field("zcbbhyf", "总成本（不含运费）（元/只）", true, false),
          new Field("gz", "工资（元/只）", true, false),
          new Field("zzfy", "制造费用（元/只）", true, false),
          new Field("sxfy", "三项费用（元/只）", true, false),
          new Field("gzmjfwy", "工装模具费（万元）", true, false),
          new Field("rzfwy", "认证费 （万元）", true, false),
          new Field("sbfwy", "设备费（万元）", true, false),
          new Field("zjwy", "总计（万元）", true, false),
          new Field("bz", "备注", false, false),
          new Field("cpxz", "产品性质", false, false),
          new Field("xsfl", "销售分类", false, false),
          new Field("mxs", "40只柜可装数量", true, false));
  static final List<Field> SC006_MAIN =
      List.of(
          new Field("sqr", "申请人", false, false),
          new Field("sqsj", "申请时间", false, false),
          new Field("gh", "工号", false, false),
          new Field("sqdw", "申请单位", false, false),
          new Field("sqbm", "申请部门", false, false),
          new Field("sqcs", "申请处室", false, false),
          new Field("ssgs", "所属公司", false, false),
          new Field("khmc", "客户名称", false, false),
          new Field("khbh", "U9客户编号", false, true),
          new Field("khjc", "客户简称", false, true),
          new Field("khlx", "客户类型", false, false),
          new Field("ywlx1", "业务类型", false, false),
          new Field("cpsx1", "产品属性", false, false),
          new Field("xsbmyqhfrq", "销售部门要求回复日期", false, false),
          new Field("syb", "事业部（当涉及到多事业部时，请选择型号多的事业部）", false, false),
          new Field("mytk", "贸易条款", false, false),
          new Field("hl", "汇率", true, false),
          new Field("xsjgsfld", "销售价格是否联动", false, false),
          new Field("sftghwckfzdkh", "是否通过海外仓库发终端客户", false, false),
          new Field("hlldqk", "汇率联动情况", false, false),
          new Field("hsstjjhs", "核算时铜基价（含税，元/吨）", true, false),
          new Field("hssxjj", "核算时锌基价（含税，元/吨）", true, false),
          new Field("hssljjhs", "核算时铝基价（含税，元/吨）", true, false),
          new Field("hsssus316jj0", "核算时SUS316基价（含税，元/吨）", true, false),
          new Field("hsssus304jj0", "核算时SUS304基价（含税，元/吨）", true, false),
          new Field("hyfhsbz", "运费核算标准（美元）", true, false),
          new Field("bz1", "备注（业务信息）", false, false),
          new Field("sfscbj", "是否首次报价", false, false),
          new Field("jsy", "技术员", false, false),
          new Field("sfyzxldjs", "是否已执行联动计算", false, false),
          new Field("cbsfxzyh", "成本是否显著优化", false, false),
          new Field("bz", "备注（辅助信息）", false, false));
  static final List<Field> SC006_ITEM =
      List.of(
          new Field("wlxz", "物料选择", false, false),
          new Field("cpmc", "产品名称", false, false),
          new Field("khbm", "客户图号", false, false),
          new Field("u11wm", "U11位码", false, false),
          new Field("lh", "料号", false, false),
          new Field("shxh", "三花型号", false, false),
          new Field("gg", "规格", false, false),
          new Field("ysfyz", "运输费 [元/只]", true, false),
          new Field("yjnylwz", "预计年用量 [万只]", true, false),
          new Field("bzfsx", "包装方式新", false, false),
          new Field("bzfs", "包装方式", false, false),
          new Field("zcbbhs", "含运输费总成本(不含税)", true, false),
          new Field("zcb1bhs", "不含运输费总成本(不含税)", true, false),
          new Field("zjclf", "直接材料费", true, false),
          new Field("zjrgf", "直接人工费", true, false),
          new Field("zzfy", "制造费用", true, false),
          new Field("qyglf", "企业管理费", true, false),
          new Field("cbyxqy1", "成本有效期（月）", false, false),
          new Field("cbsxrq", "成本失效日期", false, false),
          new Field("sccb", "上次成本", true, true),
          new Field("cyl", "差异率", true, true),
          new Field("dzgzfyftyz", "单只工装费用分摊（元/只）", true, false),
          new Field("mjfyftyz", "模具费用分摊（元/只）", true, false),
          new Field("rzfyftyz", "认证费用分摊（元/只）", true, false),
          new Field("bz", "备注", false, false),
          new Field("cpxz", "产品性质", false, false),
          new Field("xsfl", "销售分类", false, false),
          new Field("sftslhxsxl", "是否特殊料号", false, true),
          new Field("sftsxl", "是否特殊小类", false, true),
          new Field("sfybj", "是否已报价", false, true),
          new Field("mxs", "40只柜可装数量", true, false));
  static final List<Field> SC020_MAIN =
      List.of(
          new Field("sqr", "申请人", false, false),
          new Field("sqsj", "申请时间", false, false),
          new Field("gh", "工号", false, false),
          new Field("sqdw", "申请单位", false, false),
          new Field("sqbm", "申请部门", false, false),
          new Field("sqcs", "申请处室", false, false),
          new Field("khmc", "客户名称", false, false),
          new Field("khlx", "客户类型", false, false),
          new Field("gkyqhfsj", "顾客要求回复时间", false, false),
          new Field("ywlx", "业务类型", false, false),
          new Field("cpsx", "产品属性", false, false),
          new Field("xsbmyqhfrq", "销售部门要求回复日期", false, false),
          new Field("syb", "事业部", false, false),
          new Field("mytk", "贸易条款", false, false),
          new Field("hl", "汇率", true, false),
          new Field("hlldqk", "汇率联动情况", false, false),
          new Field("xsjgsfld", "销售价格是否联动", false, false),
          new Field("hsstjjhs", "核算时铜基价（含税，元/吨）", true, false),
          new Field("hssxjj", "核算时锌基价", true, false),
          new Field("hsssus316jj0", "核算时316L基价（含税）", true, false),
          new Field("hsssus304jj0", "核算时304基价（含税）", true, false),
          new Field("hssljj", "核算时铝基价", true, false),
          new Field("hyfhsbz", "海运费核算标准", true, false),
          new Field("sfscbj", "是否首次报价", false, false),
          new Field("jsy", "技术员", false, false),
          new Field("bz", "备注（辅助信息）", false, false));
  static final List<Field> SC020_ITEM =
      List.of(
          new Field("wlxz1", "物料选择", false, false),
          new Field("khbm", "客户编码", false, false),
          new Field("dhm", "U11位码", false, false),
          new Field("lh", "料号", false, false),
          new Field("shxh", "三花型号", false, false),
          new Field("pm", "品名", false, false),
          new Field("gg", "规格", false, false),
          new Field("ysf", "运输费", true, false),
          new Field("yjnylz", "预计年用量（只）", true, false),
          new Field("bzfs", "包装方式", false, false),
          new Field("hysfzcbbhs", "含运输费总成 本(不含税)", true, false),
          new Field("bhysfzcbbhs", "不含运输费总成 本(不含税)", true, false),
          new Field("cbyxq1", "成本有效期（月）", false, false),
          new Field("bxgsu304k", "不锈钢SU304(克）", true, false),
          new Field("bxgsu316k", "不锈钢SU316(克）", true, false),
          new Field("tzk", "铜重（克）", true, false),
          new Field("bz", "备注", false, false));
  static final List<Field> SR_MAIN =
      List.of(
          new Field("sqr", "申请人", false, false),
          new Field("sqdw", "申请单位", false, false),
          new Field("sqbm", "申请部门", false, false),
          new Field("sqrq", "申请日期", false, false),
          new Field("sqrgh", "申请人工号", false, false),
          new Field("ywlx", "业务类型", false, false),
          new Field("sssybdx", "所属事业部", false, false),
          new Field("frzz", "法人组织", false, false),
          new Field("qybm", "企业编码", false, false),
          new Field("frzzbm", "法人组织编码", false, false),
          new Field("khmc", "客户名称", false, false),
          new Field("khjc", "客户简称", false, false),
          new Field("crmkhbm", "CRM客户编码", false, false),
          new Field("khyqhfrq", "客户要求回复日期", false, false),
          new Field("mytk", "贸易条款", false, false),
          new Field("sfscbj", "是否首次报价", false, false),
          new Field("qyg", "起运国", false, false),
          new Field("jsy", "技术员", false, false),
          new Field("rzxq", "是否有认证需求", false, false),
          new Field("jgbp", "价格报批", false, false),
          new Field("cpsx", "产品属性", false, false),
          new Field("hl", "汇率", true, false),
          new Field("hlldqk", "汇率联动情况", false, false),
          new Field("sftghwshxs", "是否通过海外三花销售", false, false),
          new Field("crmsjbm", "CRM商机编码", false, false),
          new Field("htpsdh", "合同评审单号", false, false),
          new Field("hsstjj", "核算时铜基价（含税）", true, false),
          new Field("xsjgldqk", "销售价格联动情况", false, false),
          new Field("hssxjjhs", "核算时锌基价（含税）", true, false),
          new Field("hssljjhs", "核算时铝基价（含税）", true, false),
          new Field("hssbxgjjhs", "核算时不锈钢基价（含税）", true, false),
          new Field("qtclj", "其他材料价", false, false),
          new Field("hssyjjhs", "核算时银基价（含税）", true, false),
          new Field("khzdcgsm", "客户指定采购说明", false, false),
          new Field("mjfyyscd", "模具费用由谁承担", false, false),
          new Field("jzhyf", "基准运输费（海运费+包干费）", true, false),
          new Field("bz1", "备注1（业务信息）", false, false),
          new Field("bz", "备注（辅助信息）", false, false),
          new Field("sfxgzsh", "是否需工资审核", false, false));
  static final List<Field> SR_BATCH_MAIN =
      List.of(
          new Field("sfxzbjstgzl", "是否需总部技术提供资料", false, false),
          new Field("cbhsyhssfscbj", "成本核算员核实是否首次报价", false, false));
  static final List<Field> SR_NEW_MAIN =
      List.of(
          new Field("xhgg", "型号规格", false, false),
          new Field("mbxsjg", "目标销售价格", true, false),
          new Field("yjnyl", "预计年用量（万只）", true, false),
          new Field("gzjjfyzjewy", "工装夹具费用总金额（万元）", true, false),
          new Field("mjfyzjewy", "模具费用总金额（万元）", true, false),
          new Field("gzjjfft", "工装夹具费分摊", true, false),
          new Field("djfy", "刀具费用", true, false),
          new Field("mjfyft", "模具费用分摊", true, false),
          new Field("mjfgs", "模具费归属", false, false),
          new Field("yfxmh", "研发项目号", false, false),
          new Field("gzwb", "单件工资", false, false),
          new Field("bfl", "报废率", true, false),
          new Field("bflsm", "报废率说明", false, false),
          new Field("cpzt", "产品状态", false, false),
          new Field("htpsddh", "合同评审单单号", false, false),
          new Field("lb", "类别", false, false),
          new Field("kxxfxhtpsd", "可行性分析合同评审单", false, false),
          new Field("rzfhs", "认证费含税", true, false),
          new Field("sj", "税金", true, false),
          new Field("rzfybhs", "认证费用（不含税）", true, false));
  static final List<Field> SR_BATCH_ITEM =
      List.of(
          new Field("cpmc", "产品名称", false, false),
          new Field("khmc", "客户图号", false, false),
          new Field("lh", "料号", false, false),
          new Field("shxh", "三花型号", false, false),
          new Field("gg", "规格", false, false),
          new Field("ysfyz", "运输费[元/只]（国际客户时必填该字段）", true, false),
          new Field("yjnylwz", "三花配套量[万只]", true, false),
          new Field("zcbbhs", "含运输费总成本（不含税）", true, false),
          new Field("cb1", "不含运输费总成本（不含税）", true, false),
          new Field("zjclf", "直接材料费", true, false),
          new Field("zjrgf", "直接人工费", true, false),
          new Field("zzfy", "制造费用", true, false),
          new Field("qyglf", "企业管理费", true, false),
          new Field("cbyxq", "成本有效期", false, false),
          new Field("bzfs", "包装方式", false, false),
          new Field("bz", "备注", false, false),
          new Field("plpmjsl", "批量品每柜数量", true, false),
          new Field("wlxz", "物料选择", false, false));
  static final List<Field> SR_NEW_ITEM =
      List.of(
          new Field("cpmc", "产品名称", false, false),
          new Field("khmc", "客户图号", false, false),
          new Field("lh", "料号", false, false),
          new Field("shxh", "型号规格", false, false),
          new Field("ysfyz", "新品运输费[元/只]（国际客户时必填该字段）", true, false),
          new Field("yjnylwz", "预计年用量[万只]", true, false),
          new Field("mbxsjg", "目标销售价格", true, false),
          new Field("hysfzcbbhs", "含运输费总成本（不含税）", true, false),
          new Field("zcbbhs", "新品不含运输费总成本（不含税）", true, false),
          new Field("gzmjfwy", "工装模具费（万元）", true, false),
          new Field("rzfwy", "认证费（万元）", true, false),
          new Field("sbfwy", "设备费（万元）", true, false),
          new Field("zjwy", "总计（万元）", true, false),
          new Field("xpjgyxq", "新品价格有效期", false, false),
          new Field("bz", "备注", false, false));
}
