package com.sanhua.marketingcost.service.technicaldata;

public enum TechnicalDataTaskErrorCode {
  INVALID_REQUEST,
  FORBIDDEN,
  TASK_NOT_FOUND,
  PRODUCT_NOT_FOUND,
  VERSION_CONFLICT,
  ACTIVE_PRODUCT_CONFLICT,
  SOURCE_CHANGE_REQUIRES_COMPLETE_TASK,
  PERSISTENCE_CONFLICT
}
