package com.sanhua.marketingcost.integration.oa.collaboration;

/** OA接口说明V0.5实际定义的完整事件集合。 */
public enum OaCollaborationEventType {
  TECH_TASK_CREATED,
  TECH_TASK_LINKED,
  TECH_TASK_UPDATED,
  TECH_TASK_COMPLETED,
  FINANCE_REVIEW_READY,
  TECH_TASK_REOPENED,
  FINANCE_REVIEW_RESUMED,
  FINANCE_REVIEW_PROCESSING,
  FINANCE_REVIEW_COMPLETED,
  APPROVED_RESULT_REUSED,
  COSTING_STARTED,
  COSTING_COMPLETED,
  COLLABORATION_CANCELLED,
  SYSTEM_SYNC_FAILED
}
