package com.sanhua.marketingcost.dto.quotebom;

import java.math.BigDecimal;

public record PackageComponentStructureLineDto(
    Long snapshotId,
    Long snapshotDetailId,
    String referenceFinishedCode,
    String sourceTopProductCode,
    String periodMonth,
    Integer lineNo,
    String packageParentCode,
    String packageParentName,
    String packageParentSpec,
    String packageParentModel,
    String packageParentDrawingNo,
    String packageParentShapeAttr,
    String packageParentMainCategoryCode,
    String packageParentUnit,
    BigDecimal packageQtyPerParent,
    BigDecimal packageQtyPerTop,
    BigDecimal packageParentBaseQty,
    Long packageSourceRawHierarchyId,
    String packageSourcePath,
    String packageChildCode,
    String packageChildName,
    String packageChildSpec,
    String packageChildModel,
    String packageChildDrawingNo,
    String packageChildShapeAttr,
    String packageChildMainCategoryCode,
    String packageChildUnit,
    BigDecimal childQtyPerParent,
    BigDecimal childQtyPerTop,
    BigDecimal childParentBaseQty,
    Long childSourceRawHierarchyId,
    String childSourceParentCode,
    String childSourcePath,
    Integer childSourceSortSeq) {}
