package com.sanhua.marketingcost.dto.quotebom;

import java.math.BigDecimal;

public record QuoteBomSourceLineDto(
    Long sourceId,
    Integer lineNo,
    Integer level,
    String topProductCode,
    String parentCode,
    String materialCode,
    String materialName,
    String materialSpec,
    String materialModel,
    String drawingNo,
    String shapeAttr,
    String mainCategoryCode,
    String mainCategoryName,
    String unit,
    String sourceCategory,
    String costElementCode,
    String bomPurpose,
    String bomVersion,
    BigDecimal qtyPerParent,
    BigDecimal qtyPerTop,
    BigDecimal parentBaseQty,
    String path,
    Integer sortSeq,
    Long sourceRawHierarchyId,
    Long sourceU9BomId,
    Integer manualFlag,
    String priceOrgCode,
    String materialOrganizationCode,
    String childType,
    String alternativeGroupKey) {

  public QuoteBomSourceLineDto(
      Long sourceId,
      Integer lineNo,
      Integer level,
      String topProductCode,
      String parentCode,
      String materialCode,
      String materialName,
      String materialSpec,
      String materialModel,
      String drawingNo,
      String shapeAttr,
      String mainCategoryCode,
      String mainCategoryName,
      String unit,
      String sourceCategory,
      String costElementCode,
      String bomPurpose,
      String bomVersion,
      BigDecimal qtyPerParent,
      BigDecimal qtyPerTop,
      BigDecimal parentBaseQty,
      String path,
      Integer sortSeq,
      Long sourceRawHierarchyId,
      Long sourceU9BomId,
      Integer manualFlag,
      String priceOrgCode,
      String materialOrganizationCode) {
    this(
        sourceId,
        lineNo,
        level,
        topProductCode,
        parentCode,
        materialCode,
        materialName,
        materialSpec,
        materialModel,
        drawingNo,
        shapeAttr,
        mainCategoryCode,
        mainCategoryName,
        unit,
        sourceCategory,
        costElementCode,
        bomPurpose,
        bomVersion,
        qtyPerParent,
        qtyPerTop,
        parentBaseQty,
        path,
        sortSeq,
        sourceRawHierarchyId,
        sourceU9BomId,
        manualFlag,
        priceOrgCode,
        materialOrganizationCode,
        null,
        null);
  }
}
